# Generated by Django 5.2.4 on 2026-01-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='uid',
        ),
    ]
